name: Docker Image CI

on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: |
        docker build -t my-docker-repo .
    - name: slack - GitHub Actions Slack integration
      uses: act10ns/slack@v2.0.0
      with:
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
        channel: '#feb-2024-weekend-batch, #feb-2020-weekend-batch'
      if: always()

